<meta charset="utf-8">
<title><%=title%></title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="Find your lost items using Find My Things.">
<meta name="author" content="Team Rocket, CS 2340 at Georgia Tech">

<!-- Le styles -->
<link href="/assets/css/bootstrap.css" rel="stylesheet">
<link rel="stylesheet" href="/assets/css/font-awesome.css">
<style type="text/css">
  body {
    padding-top: 60px;
    padding-bottom: 40px;
  }
  .input-prepend textarea {
    resize: vertical;
    -moz-border-radius-topleft: 0;
    -webkit-border-top-left-radius: 0;
    border-top-left-radius: 0;
  }
</style>
<link href="/assets/css/bootstrap-responsive.css" rel="stylesheet">

<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
  <link rel="stylesheet" href="/assets/css/font-awesome-ie7.min.css">
  <script src="/assets/js/html5shiv.js"></script>
<![endif]-->

<!-- Fav and touch icons -->
<!-- link rel="apple-touch-icon-precomposed" sizes="144x144" href="/assets/ico/apple-touch-icon-144-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/assets/ico/apple-touch-icon-114-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/assets/ico/apple-touch-icon-72-precomposed.png">
                <link rel="apple-touch-icon-precomposed" href="/assets/ico/apple-touch-icon-57-precomposed.png" -->
                               <link rel="shortcut icon" href="/assets/ico/favicon.png">
