/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-04-09 19:13:20 UTC)
 * on 2013-04-10 at 08:17:38 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.fmthings.model;

/**
 * Model definition for DBMember.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-api-java-client/wiki/Json">http://code.google.com/p/google-api-java-client/wiki/Json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class DBMember extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String address;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean admin;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime dateRegistered;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean editable;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String email;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String hashedPassword;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean locked;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String password;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private PhoneNumber phone;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean registered;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> roles;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String salt;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> stringPermissions;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAddress() {
    return address;
  }

  /**
   * @param address address or {@code null} for none
   */
  public DBMember setAddress(java.lang.String address) {
    this.address = address;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getAdmin() {
    return admin;
  }

  /**
   * @param admin admin or {@code null} for none
   */
  public DBMember setAdmin(java.lang.Boolean admin) {
    this.admin = admin;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getDateRegistered() {
    return dateRegistered;
  }

  /**
   * @param dateRegistered dateRegistered or {@code null} for none
   */
  public DBMember setDateRegistered(com.google.api.client.util.DateTime dateRegistered) {
    this.dateRegistered = dateRegistered;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getEditable() {
    return editable;
  }

  /**
   * @param editable editable or {@code null} for none
   */
  public DBMember setEditable(java.lang.Boolean editable) {
    this.editable = editable;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEmail() {
    return email;
  }

  /**
   * @param email email or {@code null} for none
   */
  public DBMember setEmail(java.lang.String email) {
    this.email = email;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getHashedPassword() {
    return hashedPassword;
  }

  /**
   * @param hashedPassword hashedPassword or {@code null} for none
   */
  public DBMember setHashedPassword(java.lang.String hashedPassword) {
    this.hashedPassword = hashedPassword;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getLocked() {
    return locked;
  }

  /**
   * @param locked locked or {@code null} for none
   */
  public DBMember setLocked(java.lang.Boolean locked) {
    this.locked = locked;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public DBMember setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPassword() {
    return password;
  }

  /**
   * @param password password or {@code null} for none
   */
  public DBMember setPassword(java.lang.String password) {
    this.password = password;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public PhoneNumber getPhone() {
    return phone;
  }

  /**
   * @param phone phone or {@code null} for none
   */
  public DBMember setPhone(PhoneNumber phone) {
    this.phone = phone;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getRegistered() {
    return registered;
  }

  /**
   * @param registered registered or {@code null} for none
   */
  public DBMember setRegistered(java.lang.Boolean registered) {
    this.registered = registered;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getRoles() {
    return roles;
  }

  /**
   * @param roles roles or {@code null} for none
   */
  public DBMember setRoles(java.util.List<java.lang.String> roles) {
    this.roles = roles;
    return this;
  }

  /**
   * @see #decodeSalt()
   * @return value or {@code null} for none
   */
  public java.lang.String getSalt() {
    return salt;
  }

  /**

   * @see #getSalt()
   * @return Base64 decoded value or {@code null} for none
   *
   * @since 1.14
   */
  public byte[] decodeSalt() {
    return com.google.api.client.util.Base64.decodeBase64(salt);
  }

  /**
   * @see #encodeSalt()
   * @param salt salt or {@code null} for none
   */
  public DBMember setSalt(java.lang.String salt) {
    this.salt = salt;
    return this;
  }

  /**

   * @see #setSalt()
   *
   * <p>
   * The value is encoded Base64 or {@code null} for none.
   * </p>
   *
   * @since 1.14
   */
  public DBMember encodeSalt(byte[] salt) {
    this.salt = com.google.api.client.util.Base64.encodeBase64URLSafeString(salt);
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getStringPermissions() {
    return stringPermissions;
  }

  /**
   * @param stringPermissions stringPermissions or {@code null} for none
   */
  public DBMember setStringPermissions(java.util.List<java.lang.String> stringPermissions) {
    this.stringPermissions = stringPermissions;
    return this;
  }

  @Override
  public DBMember set(String fieldName, Object value) {
    return (DBMember) super.set(fieldName, value);
  }

  @Override
  public DBMember clone() {
    return (DBMember) super.clone();
  }

}
