[#ftl]
[#macro authenticated][/#macro]
[#macro notAuthenticated][/#macro]
[#macro guest][/#macro]
[#macro user][/#macro]
[#macro hasAnyRoles][/#macro]
[#macro hasPermission name][/#macro]
[#macro lacksPermission name][/#macro]
[#macro hasRole name][/#macro]
[#macro lacksRole name][/#macro]
[#macro principal type property][/#macro]